// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ytgmzhevgcmvevuwkocz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Z216aGV2Z2NtdmV2dXdrb2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzA5NDgsImV4cCI6MjA2NjIwNjk0OH0.yOoZd4w7sURBnsQuGb1custfkz1_g5MGt9skysV1fPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
